const contact = {
  email: 'arturogallardojr@hotmail.com',
  phone: '+52 33 3958 2488',
  wa: 'https://wa.me/523339582488',
  linkedin: 'https://www.linkedin.com/in/arturo-javier-gallardo-ruvalcaba',
  github: 'https://github.com/ArturoGallardoR',
};

export const C = {
  en: {
    title: 'AI-First Tech Builder, automation, ERP and cloud systems.',
    loader: ['Arturo Gallardo', 'Guadalajara, MX'],
    menu: 'Menu',
    close: 'Close',
    nav: [['about', 'About'], ['work', 'Work'], ['contact', 'Contact']],
    spy: [['about', 'Statement'], ['services', 'Capabilities'], ['work', 'Work'], ['contact', 'Contact']],
    info: [['Email', contact.email, `mailto:${contact.email}`], ['WhatsApp', contact.phone, contact.wa]],
    heroDesc: ['From objective to production: I build the AI,', 'automation and ERP links myself, and measure', 'them by what changes each day.'],
    heroTitle: ['AI-First Tech Builder', 'and Automation Engineer.'],
    scroll: 'Scroll to see the work',
    about: [
      "I'm a hands-on technology builder. You bring a business objective and I",
      'ship a working solution that runs in production, wiring together ERP,',
      'CRM, AI models, cloud infrastructure and automation. I do it on my own,',
      'with no external development team in between.',
    ],
    dvTitle: ['From four hours to 8', 'seconds.'],
    dvText: ['LinkedIn feeds n8n, AI cleans and scores the lead,', "and it lands in Odoo CRM. It's the signature", 'automation in my role at 121 LLC.'],
    dvHud: ['RAW PUBLIC DATA', 'PIPELINE / ONE LEAD', 'BEFORE / 4 HOURS', 'NOW / ~8 SECONDS'],
    dvCaption: ['One pipeline in production: public data goes', 'in, a clean business record comes out, and the', 'whole trip takes seconds, about 8 per lead.'],
    svcTitle: ['One builder, from goal', 'to production.'],
    svcText: [
      'I take the objective and ship the system behind it: AI, automation, cloud and the',
      'ERP and CRM it has to talk to. No external development team, and the measure',
      'is simple: what changes in your daily operations.',
    ],
    cards: [
      { t: ['AI agents', 'on live data'], x: ['Custom MCP servers that let AI agents read', 'live Odoo ERP and CRM data, plus full-stack', 'AI apps I design and deploy myself, from', 'design to production.'] },
      { t: ['Automation', 'pipelines'], x: ['Pipelines in n8n that take work off people:', 'a prospecting flow went from 4 hours of manual', 'work a day to about 8 seconds per lead, and', 'the lead lands in Odoo.'] },
      { t: ['Endpoints', 'and IT ops'], x: ['NinjaOne across about 100 endpoints, five', 'management policies I designed, plus Google', 'Workspace, Active Directory and network', "infrastructure I've run."] },
    ],
    casesTitle: ['Selected work,', 'built since 2017.'],
    casesText: ['Six systems I built and put into production, each one measured by what it changed.', 'Open a case to see the stack, the numbers and the result it had on the day-to-day operation.'],
    rowLabels: ['Stack', 'Outcome'],
    rows: [
      { t: 'Custom MCP for Odoo', y: '[Live ERP]', k: 'AI · Integration', d: 'A Model Context Protocol server that lets AI agents query and interact with live Odoo ERP and CRM data. It keeps the model tied to real business context.', s: 'Node.js, MCP, Odoo, RAG, Anthropic API', o: 'Agents query production ERP and CRM records in real time.' },
      { t: 'LinkedIn → Odoo pipeline', y: '[~8s / lead]', k: 'Automation pipeline', d: 'A Tampermonkey button pulls public LinkedIn data, fires an n8n pipeline, AI cleans and enriches it, and the lead lands in Odoo CRM. 10 to 20 leads a week.', s: 'Tampermonkey, n8n, Odoo CRM, OpenRouter, AI cleaning', o: 'Prospecting went from 4 hours a day to about 8 seconds per lead.' },
      { t: 'Full-stack AI systems', y: '[Prod]', k: 'AI applications', d: 'Frontend and backend AI applications I designed and deployed myself, from design to production, for real business workflows.', s: 'Node.js, Cloudflare Workers, Supabase, Neon, Claude Code, OpenRouter, Orca, StageWise', o: 'Applications that went from design to production.' },
      { t: 'Corporate HTML signatures', y: '[<1 min]', k: 'Internal tool', d: 'An email signature generator built on Google Sheets and Drive, with the assets hosted on Cloudflare R2. One signature at a time or a full batch.', s: 'Google Sheets, Google Drive, Cloudflare R2, HTML/CSS', o: 'A process that used to eat a week now takes seconds.' },
      { t: 'NinjaOne endpoints', y: '[~100]', k: 'IT operations', d: 'NinjaOne across about 100 endpoints (80 Mac, 20 Windows, iPhone), five management policies designed, and the ITAM module negotiated at near-zero cost.', s: 'NinjaOne, ITAM, MDM, Windows, macOS', o: 'Every endpoint visible and controlled from one place.' },
      { t: 'HR incidents form', y: '[Pilot]', k: 'Internal automation', d: 'An HR incidents form built with n8n Forms and Cloudflare Access. Only leaders can reach it, it detects who is filling it in, and the employee list syncs from Google Sheets.', s: 'n8n Forms, Cloudflare Access, Google Sheets', o: 'About 15 leaders use it for HR incident intake in the pilot.' },
    ],
    callTitle: ["Let's build the", 'system'],
    callText: ['Open to projects and opportunities right now.', 'The work here beats a CV.'],
    cta: 'Write me on WhatsApp',
    marquee: "Let's build",
    infoLabel: 'Contact information',
    end: ['Guadalajara, Jalisco, Mexico', 'Back to top'],
    credits: '© 2026 Arturo Javier Gallardo Ruvalcaba',
  },
  es: {
    title: 'AI-First Tech Builder: IA, automatización, ERP y nube.',
    loader: ['Arturo Gallardo', 'Guadalajara, MX'],
    menu: 'Menú',
    close: 'Cerrar',
    nav: [['about', 'Sobre mí'], ['work', 'Proyectos'], ['contact', 'Contacto']],
    spy: [['about', 'Statement'], ['services', 'Capabilities'], ['work', 'Work'], ['contact', 'Contact']],
    info: [['Correo', contact.email, `mailto:${contact.email}`], ['WhatsApp', contact.phone, contact.wa]],
    heroDesc: ['Del objetivo a producción: construyo la IA,', 'la automatización y el enlace al ERP, y lo', 'mido por lo que cambia cada día.'],
    heroTitle: ['AI-First Tech Builder', 'and Automation Engineer.'],
    scroll: 'Desliza para explorar',
    about: [
      'Soy un technology builder con perfil práctico. Me das un objetivo y',
      'entrego una solución que funciona y corre en producción, uniendo ERP,',
      'CRM, modelos de IA, nube y automatización. Lo hago por mi cuenta, sin',
      'pasarle el trabajo a un equipo externo de desarrollo.',
    ],
    dvTitle: ['De cuatro horas a 8', 'segundos.'],
    dvText: ['LinkedIn alimenta n8n, la IA limpia y puntúa, y', 'el lead queda en Odoo CRM. Es la automatización', 'insignia de mi rol en 121 LLC.'],
    dvHud: ['DATOS PÚBLICOS', 'PIPELINE / UN LEAD', 'ANTES / 4 HORAS', 'AHORA / ~8 SEGUNDOS'],
    dvCaption: ['Un pipeline corriendo en producción: entran', 'datos públicos, sale un registro de negocio', 'limpio y todo tarda unos 8 segundos por lead.'],
    svcTitle: ['Un builder, de la meta', 'a producción.'],
    svcText: [
      'Tomo el objetivo y entrego el sistema detrás: IA, automatización, nube y el ERP',
      'y CRM con los que tiene que hablar. Sin equipo externo de desarrollo, y lo mido',
      'por lo que cambia en la operación diaria.',
    ],
    cards: [
      { t: ['Agentes IA', 'con datos vivos'], x: ['Servidores MCP a medida para que los agentes', 'de IA lean datos vivos del ERP y CRM de Odoo,', 'y apps full-stack que diseño y despliego', 'yo mismo, hasta producción.'] },
      { t: ['Pipelines de', 'automatización'], x: ['Pipelines en n8n que quitan trabajo manual:', 'la prospección pasó de 4 horas al día a unos', '8 segundos por lead, y el lead entra directo', 'en Odoo CRM sin captura manual.'] },
      { t: ['Endpoints', 'y operación TI'], x: ['NinjaOne en unos 100 endpoints, con las cinco', 'políticas de gestión que diseñé, más Google', 'Workspace, Active Directory e infraestructura', 'de red que he administrado.'] },
    ],
    casesTitle: ['Trabajo elegido,', 'hecho desde 2017.'],
    casesText: ['Seis sistemas que construí y puse en producción, cada uno medido por lo que cambió.', 'Abre un caso para ver el stack, los números y el efecto que tuvo en la operación diaria.'],
    rowLabels: ['Stack', 'Resultado'],
    rows: [
      { t: 'MCP para Odoo', y: '[ERP vivo]', k: 'IA · Integración', d: 'Un servidor de Model Context Protocol que permite a los agentes de IA consultar e interactuar con datos vivos del ERP y CRM de Odoo. Mantiene el modelo atado al contexto real del negocio.', s: 'Node.js, MCP, Odoo, RAG, Anthropic API', o: 'Los agentes consultan registros de producción del ERP y CRM en tiempo real.' },
      { t: 'Pipeline LinkedIn → Odoo', y: '[~8s / lead]', k: 'Pipeline de automatización', d: 'Un botón de Tampermonkey extrae datos públicos de LinkedIn, dispara un pipeline en n8n, la IA limpia y enriquece, y el lead queda en Odoo CRM. De 10 a 20 leads por semana.', s: 'Tampermonkey, n8n, Odoo CRM, OpenRouter, Limpieza con IA', o: 'La prospección pasó de 4 horas al día a unos 8 segundos por lead.' },
      { t: 'Sistemas full-stack de IA', y: '[Prod]', k: 'Aplicaciones de IA', d: 'Aplicaciones de IA de frontend y backend que diseñé y desplegué yo mismo, del diseño a producción, para flujos de trabajo reales de negocio.', s: 'Node.js, Cloudflare Workers, Supabase, Neon, Claude Code, OpenRouter, Orca, StageWise', o: 'Aplicaciones que pasaron del diseño a producción.' },
      { t: 'Firmas HTML corporativas', y: '[<1 min]', k: 'Herramienta interna', d: 'Un generador de firmas de correo sobre Google Sheets y Drive, con los activos en Cloudflare R2. Una firma a la vez o un lote completo.', s: 'Google Sheets, Google Drive, Cloudflare R2, HTML/CSS', o: 'Un proceso que se comía una semana ahora tarda segundos.' },
      { t: 'Endpoints con NinjaOne', y: '[~100]', k: 'Operaciones de TI', d: 'NinjaOne en unos 100 endpoints (80 Mac, 20 Windows, iPhone), cinco políticas de gestión diseñadas y el módulo ITAM negociado a costo casi nulo.', s: 'NinjaOne, ITAM, MDM, Windows, macOS', o: 'Todos los endpoints visibles y controlados desde un solo lugar.' },
      { t: 'Formulario de RH', y: '[Piloto]', k: 'Automatización interna', d: 'Un formulario de incidentes de RH con n8n Forms y Cloudflare Access. Solo entran los líderes, detecta quién lo llena y la lista de empleados se sincroniza desde Google Sheets.', s: 'n8n Forms, Cloudflare Access, Google Sheets', o: 'Unos 15 líderes lo usan para levantar incidentes de RH en el piloto.' },
    ],
    callTitle: ['Construyamos algo', 'grande'],
    callText: ['Abierto a proyectos y oportunidades ahora.', 'Aquí el trabajo pesa más que un CV.'],
    cta: 'Escríbeme por WhatsApp',
    marquee: 'Construyamos',
    infoLabel: 'Información de contacto',
    end: ['Guadalajara, Jalisco, México', 'Volver arriba'],
    credits: '© 2026 Arturo Javier Gallardo Ruvalcaba',
  },
};

export const LINKS = contact;
